services:
  - type: web
    name: ihsebli
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: IHSEBLI_DATA
        value: /data
